### ISSUE TITLE
feature: prevent check delay on startup

### ISSUE THREAD

**Issue by MorphBonehunter** [lrstanley/vault-unseal#20]
### ✨ Describe the feature you'd like

At the moment the first execution of the seal check is delayed for the CheckInterval because of the time.After statement in the "daemon.go".
So it would be cool if this would be executed immediately after startup of vault-unseal.  

### 🌧 Is your feature request related to a problem?

Not really an problem but an question if this is intentional.
Imagine an high value of CheckInterval (say 300s), so the first check would occur 5m after startup.

### 🔎 Describe alternatives you've considered

As I'm not an programmer I'm not able to provide a solution for this out of the box.
Maybe the main part of the for loop could be an function so that this could be called once
before the loop starts 🤷 but I'm not sure if this works with the select stuff in golang.

### ⚠ If implemented, do you think this feature will be a breaking change to users?

No

### 🤝 Requirements

- [X] I have confirmed that someone else has not [submitted a similar feature request](../labels/enhancement).
- [X] If implemented, I believe this feature will help others, in addition to solving my problems.
- [X] I have looked into alternative solutions to the best of my ability.
- [X] (optional) I would be willing to contribute to testing this feature if implemented, or making a PR to implement this functionality.

**Comment by lrstanley** [comment]
Yep, this is an intentional design choice, to prevent thundering herd scenarios.

Generally, the check interval should be lower than something like 5min, though its worth noting that even if the initial interval didn't exist, there is still a potential for the same time delay scenario to exist, if vault is restarted but vault-unseal is not. I think having the initial delay makes it clear what the potential downsides are of having a longer check duration, and also prevents thundering herd scenarios for very low check intervals.
